##  Name of the workflow.
name: TechTrends - Package with Docker


## Set the trigger policy.
## In this case, the workflow is executed on a pull request event,
## or when a new commit is pushed to the main branch.
on:
  push:
    branches: [ 'main' ]

## List the steps to be executed by the workflow
jobs:
  ## Set the name of the job  
  build:
    ## Configure the operating system the workflow should run on.
    ## In this case, the job run on Ubuntu.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    ## Define a sequence of steps to be executed
    steps:
        ## Use the public `checkout` action  in version v2  
        ## to checkout the existing code in the repository
      -
        name: Checkout
        uses: actions/checkout@v2
        ## Use the public `setup-python` actoin  in version v2  
        ## to install python on the Ubuntu based environment.
        ## Additionally, it ensures to loop through all 
        ## the defined Python versions.
      - 
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      ## Install all necessary dependecies .
      ## For example, any defined packages within the requirements.txt file.
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      ## Run commands
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: afcarval/techtrends1:latest
